name: Solar System Deployment Workflow

on: 
    workflow_dispatch:
    push:
        branches:
            - main


jobs:
    unit-testing:
        name: Unit Testing of Solar-System
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up NodeJS Version
              uses: actions/setup-node@v4
              with: 
                node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Unit Testing
              run: npm test


            
            